name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./C:\Users\Administrator\Desktop\practice\Practice-Tool\practice\WebApplication1
    - name: Build
      run: dotnet build --no-restore ./C:\Users\Administrator\Desktop\practice\Practice-Tool\practice\WebApplication1
    - name: Test
      run: dotnet test --no-build --verbosity normal ./C:\Users\Administrator\Desktop\practice\Practice-Tool\practice\WebApplication1
